ALTER TABLE readers ADD COLUMN name TEXT NOT NULL DEFAULT '';
ALTER TABLE readers ADD COLUMN surname TEXT NOT NULL DEFAULT '';
ALTER TABLE readers ADD COLUMN email TEXT NOT NULL DEFAULT '';
ALTER TABLE readers ADD COLUMN telephone TEXT NOT NULL DEFAULT '';
ALTER TABLE readers ADD COLUMN password TEXT NOT NULL DEFAULT '';

CREATE UNIQUE INDEX IF NOT EXISTS uk_readers_email ON readers (email) WHERE email <> '';
